CREATE TABLE `Brain_Morphology` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`IRC5_Reviewer` varchar(255) default NULL,
`IRC5_Reviewer_status` enum('not_answered') default NULL,
`BDRPBestDxType` enum('10','53','54','52','55','56') default NULL,
`BDRPBestDxTypeLvlOfConfid` enum('101','102','103','104','105','106','107','108','109','110') default NULL,
`CorpusCallosumType` enum('10','50','51','52','56','95') default NULL,
`BDRPBestDxDescription` varchar(255) default NULL,
`BDRPBestDxDescription_status` enum('not_answered') default NULL,
`DandyWalkerMalformation` enum('0','1') default NULL,
`AntCommisNlAb` enum('10','11','12','0','95') default NULL,
`HipCommisNlAb` enum('10','11','12','0','95') default NULL,
`PituitaryNlAb` enum('10','9','95') default NULL,
`BrainstemNIAb` enum('10','9','95') default NULL,
`CerebellarHemispheresNlAb` enum('10','9','95') default NULL,
`CerebellarVermisNlAb` enum('10','9','95') default NULL,
`CerebellarPendunclesDescriptioin` enum('10','9','95') default NULL,
`CM` enum('0','1','95') default NULL,
`PMG` enum('0','1','95') default NULL,
`PVHeterotopia` enum('0','1','95') default NULL,
`SCHeterotopia` enum('0','1','95') default NULL,
`Schizencephaly` enum('0','1','95') default NULL,
`DysplasiaNOS` enum('0','1','95') default NULL,
`VentricleNlAb` enum('0','9','95') default NULL,
`VentricleDysplasia` enum('0','1','95') default NULL,
`VentricleSize` enum('10','11','12','95') default NULL,
`Colpocephaly` enum('0','1','95') default NULL,
`BasalGangliaThalamus` enum('0','1','95') default NULL,
`OrbitsNlAb` enum('10','9','95') default NULL,
`HippocampiNlAb` enum('10','9','95') default NULL,
`SulciNlAb` enum('10','9','95') default NULL,
`BulbsNlAb` enum('10','9','95') default NULL,
`LipomaNonePresent` enum('0','1','95') default NULL,
`CystPresAbs` enum('0','1','95') default NULL,
`CystType` enum('0','1','2','56','95') default NULL,
`ProbstBundlesNonePresent` enum('0','1','95') default NULL,
`SigBundlesNonePresent` enum('0','1','95') default NULL,
`WMDecAmt` enum('23','24','95') default NULL,
`WMVolumeNLDec` enum('10','11','95') default NULL,
`MyelinationNlAb` enum('10','9','95') default NULL,
`OtherMRIFindings` enum('1','2') default NULL,
`OtherMRIFindingsDescribe` varchar(255) default NULL,
`OtherMRIFindingsDescribe_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('Brain_Morphology', 'Brain_Morphology', 1);
