CREATE TABLE `PhysicianEvaluation` (
`CommentID` varchar(255) NOT NULL default '',
                          `UserID` varchar(255) default NULL,
                          `Examiner` varchar(255) default NULL,
                          `Testdate` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                          `Data_entry_completion_status` enum('Incomplete','Complete') NOT NULL default 'Incomplete',
`Date_taken` date default NULL,
`Candidate_Age` varchar(255) default NULL,
`Window_Difference` varchar(255) default NULL,
`NeurologyReport` enum('0','1','97','not_answered') default NULL,
`NeurologyReportDate` date default NULL,
`NeurologyReportDate_status` enum('not_answered') default NULL,
`GeneticsEvaluationRpt` enum('0','1','97','not_answered') default NULL,
`GeneticsEvaluationRptDate` date default NULL,
`GeneticsEvaluationRptDate_status` enum('not_answered') default NULL,
`DevelopmentalPedRpt` enum('0','1','97','not_answered') default NULL,
`DevelopmentalPedRptDate` date default NULL,
`DevelopmentalPedRptDate_status` enum('not_answered') default NULL,
`OphthalmologyEvaluationRpt` enum('0','1','97','not_answered') default NULL,
`OphthalmologyEvaluationRptDate` date default NULL,
`OphthalmologyEvaluationRptDate_status` enum('not_answered') default NULL,
`AudiologyRpt` enum('0','1','97','not_answered') default NULL,
`AudiologyRptDate` date default NULL,
`AudiologyRptDate_status` enum('not_answered') default NULL,
`EndocrinologyRpt` enum('0','1','97','not_answered') default NULL,
`EndocrinologyRptDate` date default NULL,
`EndocrinologyRptDate_status` enum('not_answered') default NULL,
`OrthopedicEvaluationRpt` enum('0','1','97','not_answered') default NULL,
`OrthopedicEvaluationRptDate` date default NULL,
`OrthopedicEvaluationRptDate_status` enum('not_answered') default NULL,
`PsychiatricEvaluationRpt` enum('0','1','97','not_answered') default NULL,
`PsychiatricEvaluationRptDate` date default NULL,
`PsychiatricEvaluationRptDate_status` enum('not_answered') default NULL,
`MedicalHistory` enum('0','1','97','not_answered') default NULL,
`MedicalHistoryDate` date default NULL,
`MedicalHistoryDate_status` enum('not_answered') default NULL,
`RecentPhysical` enum('0','1','97','not_answered') default NULL,
`RecentPhysicalDate` date default NULL,
`RecentPhysicalDate_status` enum('not_answered') default NULL,
`ClinicalEvaluationForm` enum('0','1','97','not_answered') default NULL,
`ClinicalEvaluationFormDAte` date default NULL,
`ClinicalEvaluationFormDAte_status` enum('not_answered') default NULL,
`MRIReport` enum('0','1','97','not_answered') default NULL,
`MRIReportDate` date default NULL,
`MRIReportDate_status` enum('not_answered') default NULL,
`GIReport` enum('0','1','97','not_answered') default NULL,
`GIReportDate` date default NULL,
`GIReportDate_status` enum('not_answered') default NULL,
`OtherSpecialistReport` varchar(255) default NULL,
`OtherSpecialistReport_status` enum('not_answered') default NULL,
`OtherSpecialistReport Date` date default NULL,
`OtherSpecialistReport Date_status` enum('not_answered') default NULL,
PRIMARY KEY  (`CommentID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
REPLACE INTO test_names (Test_name, Full_name, Sub_group) VALUES ('PhysicianEvaluation', 'PhysicianEvaluation', 1);
