version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=LorisDB
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3306:3306"

  couchdb:
    image: couchdb:2.1
    restart: always
    ports:
      - "5984:5984"

  webapp:
    image: loris:20
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - LORIS_SQL_DB=LorisDB
      - LORIS_SQL_USER=loris
      - LORIS_SQL_HOST=mysql
      - LORIS_SQL_PASSWORD=LorisDBPASSWORD
    depends_on:
      - db
      - couchdb
    ports:
      - "${EXTERNAL_PORT:-80}:80"