version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=LORIS_19
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3306:3306"

  couchdb:
    image: couchdb:2.1
    restart: always
    ports:
      - "5984:5984"

  webapp:
    image: loris:19
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    depends_on:
      - db
      - couchdb
    ports:
      - "8081:80"