version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=LORIS_19
      - MYSQL_RANDOM_ROOT_PASSWORD=true

  webapp:
    image: loris
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.production
    depends_on:
      - db
    ports:
      - "80:80"