version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - docker/envs/default.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-LorisPass}
    ports:
      - "3306:3306"

  couchdb:
    image: couchdb:2.1
    restart: always
    ports:
      - "5984:5984"

  webapp:
    image: loris:20
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - docker/envs/default.env
    depends_on:
      - db
      - couchdb
    ports:
      - "${EXTERNAL_PORT:-80}:80"