version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - docker/envs/default.env
    ports:
      - "3306:3306"

  couchdb:
    image: couchdb:2.1
    restart: always
    ports:
      - "5984:5984"

  webapp:
    image: loris:${LORIS_VERSION:-dev}
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - docker/envs/default.env
    depends_on:
      - db
      - couchdb
    ports:
      - "${LORIS_PORT:-80}:80"