version: '3'

services:
  db:
    env_file:
      - docker/envs/prod.env
    volumes:
      - ./backup:/backup

  couchdb:
    volumes:
      - ../backup:/backup

  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile.production
      args:
        LORIS_TAG: v20.0.1
    env_file:
      - docker/envs/prod.env
    volumes:
      - ../backup:/backup