version: '3'

services:
  db:
    env_file:
      - docker/envs/prod.env
    environment:
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ../backup/db:/backup

  couchdb:
    volumes:
      - ../backup/couchdb:/backup

  webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        LORIS_TAG: v20.0.1
    env_file:
      - docker/envs/prod.env
    volumes:
      - ../backup/loris:/backup