version: '3'

services:
  db:
    env_file:
      - docker/envs/prod.env
    environment:
      - MYSQL_ROOT_PASSWORD=

  webapp:
    env_file:
      - docker/envs/prod.env
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        LORIS_VERSION: "${LORIS_VERSION:-v20.0.1}"
    volumes:
      - ../backup:/backup